### ISSUE TITLE
"already existing zip-file" warning of benchexec hinders workflow

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#502] opened 2019-11-12 07:29 UTC
When testing stuff, it always happens to me that I have to manually delete the zip files in case I want to execute `benchmark.py` more than once in the same minute:

Observed behavior:

```
$ benchexec test.xml
Output archive results/test.2019-11-12_0654.logfiles.zip already exists, will not overwrite existing results.
$ rm results/test.2019-11-12_0654.logfiles.zip
$ benchexec test.xml
[...]
```

Possible improvement:

```
$ benchexec test.xml --interactive
Output archive results/test.2019-11-12_0654.logfiles.zip already exists, do you want to overwrite it? [Y/n]
Y
[...] #delete the zip and proceeeding as intended by the user
```

**Comment by PhilippWendler** [comment] 2019-11-12 08:02
Ideally, the ZIP should be created lazily as soon as the first result is written, then this would not happen. We do this already for the XML files.

**Comment by MartinSpiessl** [comment] 2019-11-12 10:27
This would definitely be an improvement. However, sometimes I also wait for the first result, then abort, inspect, and then re-execute, in which case the zip file still would be created.  
I guess adding the seconds to the zip name would not be backwards-compatible, or is there another reason for not just adding this?

**Comment by PhilippWendler** [comment] 2019-11-25 18:02
That is suggested in #283.

**Comment by kfriedberger** [comment] 2020-04-06 12:10
Just a note: the `table-generator` does simply override existing tables without any warning.
Of course, creating a table is much cheaper than running a full benchmark.
Nevertheless, the behavior is inconsistent between `benchexec` and `table-generator`.

**Comment by PhilippWendler** [comment] 2020-06-09 10:57
@kfriedberger It is not about being "cheap". Overwriting a table does not destroy data, because a table can be regenerated from the raw results. But the raw results themselves might not be reproducible. Of course, if the creation of the raw results is just a minute ago, this seems unlikely, but it is still certainly better to err on the safe side.

I marked #283 for [release 3.0](https://github.com/sosy-lab/benchexec/milestone/8) and will close this because #283 will solve it well enough.

**Closed by PhilippWendler** 2020-06-09 10:57 UTC
