### ISSUE TITLE
Provide Run Options to determine_result of Tool-Info Module

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#166] opened 2016-12-04 09:35 UTC
The tool-info module for CBMC assigns values to `self.options` and reads them in `determine_result`. This is problematic because there can be several calls to `cmdline` before a call to `determine_result`, so the value of `self.options` might not belong to the run for which `determine_result` is called. `determine_result` should instead look at the output of the tool to detect the mode in which it was called.

The tool-info module for Impara contains the same code and should also be fixed.

**Comment by tautschnig** [comment] 2016-12-04 12:17
Wouldn't it be possible to provide the options to `determine_result`? The code in `determine_result` is fixable, but `parseXML` relies on that information as well as a result may or may not be inconclusive, depending on the options chosen by the user.

**Comment by PhilippWendler** [comment] 2016-12-04 13:37
It would be possible, yes, but it would be backwards-incompatible with existing tool-info modules, so I'd like to avoid it.

Could we detect from the CBMC output whether this option was specified?

**Comment by tautschnig** [comment] 2016-12-04 14:07
No, CBMC does not output how loops are being handled. (And neither would it output other options that could be of interest, such as 32/64 bits.) Overall I think it is dangerous to look at output without information about command line options, unless tools are forced to reproduce all configuration options as part of the output.

I do see that this would imply changes across all tool-info modules, and understand the concerns in doing so. In my opinion, going for kwargs would be the best approach as it adds flexibility for future developments.

**Comment by MartinSpiessl** [comment] 2019-11-27 05:20
> I do see that this would imply changes across all tool-info modules, and understand the concerns in doing so. In my opinion, going for kwargs would be the best approach as it adds flexibility for future developments.

I agree on that point.
@PhilippWendler  is it really that difficult to add `**kwargs` to all the implementations of `determine_result`. This should be straight forward and I do not see how this could possibly break existing code.

Turns out I would really need this feature (options beeing passed to `determine_result`) for classifying the output of metaval correctly. Since metaval has options to use a different verifier backend, and the result determination depends on which verifier backend is chosen, there is really no way to choose the right action in `determine_result` for the job if I do not know the options. As a workaround, I can add an ugly heuristic which will guess which tool was executed based on the output now.

**Comment by PhilippWendler** [comment] 2019-11-27 05:35
> @PhilippWendler is it really that difficult to add `**kwargs` to all the implementations of `determine_result`. This should be straight forward and I do not see how this could possibly break existing code.

Of course it breaks existing code, after all you yourself say that `**kwargs` needs to be added to all existing implementations.

**Comment by MartinSpiessl** [comment] 2019-11-27 06:17
I meant that by adding `**kwargs` to all the tools in `benchexec/tools`, we will not break anything.

Or do you expect there to be people with their own tool-info modules in their private codebase/fork and are concerned about breaking compatibility with them?

**Comment by PhilippWendler** [comment] 2019-11-27 07:19
> Or do you expect there to be people with their own tool-info modules in their private codebase/fork and are concerned about breaking compatibility with them?

Yes, it is an intended and [documented](https://github.com/sosy-lab/benchexec/blob/master/doc/tool-integration.md) use case to install BenchExec as usual and use it together with your own locally developed tool-info modules, there is no need to fork BenchExec or install it from source for this.

**Comment by MartinSpiessl** [comment] 2019-11-27 07:22
I see, thanks for clarification!

So maybe add this in the next major release (probably BenchExec 3)? Can we attach a label/milestone for that?

Or is this a case of "won't fix" and the issue can be closed?

**Comment by PhilippWendler** [comment] 2019-11-27 07:38
No, it is definitely not a "won't fix" and should not be closed, but I cannot promise any ETA nor a specific release where this will land.

**Closed** 2020-09-26 08:47 UTC
Labels: tool support
