### ISSUE TITLE
Skip execution if required files missing?

### ISSUE THREAD

**Issue by sim642** [sosy-lab/benchexec#842] opened 2022-09-19 09:29 UTC
Currently, if required files are missing, only a warning is printed:
https://github.com/sosy-lab/benchexec/blob/2b5d1fb2d1a806da397af528e79412a74aa2cda1/benchexec/model.py#L400-L404
But the tool is executed nevertheless.

Is there any reason to still execute the tool in such cases? If the file is _required_, then the tool inevitably errors sooner or later, otherwise the file wouldn't really be required.
In particular, when setting up witness validators, they get executed even for all the tasks that the verifier didn't for whatever reason produce a witness (including all the cases it errored, timed out, etc.). Seems like it would be cleaner to just skip execution in such cases and have a dash or something as the status (like when a validator tool doesn't get executed because the expected verdict filter doesn't match).

**Comment by PhilippWendler** [comment] 2022-10-04 05:53
The thing is that `<requiredfiles>` specifies a file *pattern*, not a specific file. So even if this were changed, it could still happen that a run is executed without all required files, for example if the pattern is supposed to match two files, but only one is present. We can only detect the case where none of the required files happen to be present. But this is only a heuristic instead of a precise check, and because of this and for consistency there is just the warning instead of the run being filtered out. Furthermore, `<requiredfiles>` currently does not have any influence on local benchmark execution at all, it only exists for cases where people combine BenchExec with other tools in order to recreate run environments on other tools.

I guess in principle we could add an attribute that makes at least one matching file a hard requirement for the run, but it would be low priority to add this.

**Comment by dbeyer** [comment] 2023-02-03 16:17
Duplicate of https://github.com/sosy-lab/benchexec/issues/785

**Closed** 2023-02-03 18:22 UTC
Labels: duplicate
