### ISSUE TITLE
Debian Package in Ubuntu Repository

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#613] opened 2020-09-30 17:25 UTC
Make it easy to install: sudo apt install benchexec

**Comment by dbeyer** [comment] 2020-09-30 17:29
Perhaps this can be done in two steps:
1. SoSy repository
2. Ubuntu universe repository

**Comment by dbeyer** [comment] 2020-09-30 17:30
Assigned @MartinSpiessl because he gave that a thought already and he could say something about this.

**Comment by PhilippWendler** [comment] 2020-10-01 05:23
A PPA is great, but I think we won't gain anything from trying to add it to Ubuntu itself. This will just lead to people trying to use the Ubuntu version, which would typically be years old.

**Comment by dbeyer** [comment] 2020-10-01 08:56
Let's start with PPA then.

**Comment by MartinSpiessl** [comment] 2020-10-01 10:48
With adding it to Ubuntu you probably mean getting it into the universe (or even main, but that is a stretch goal) package sources. I agree, my prediction is that this would come with some maintenance overhead indeed, outdated packages however would then be completely our fault (but updating it for different ubuntu versiosn would cost some time investment, that is probably why so many foss developers are behind schedule that much).

The natural process is to start with a PPA in any case :wink:

**Comment by PhilippWendler** [comment] 2020-10-01 11:14
> outdated packages however would then be completely our fault

No, Ubuntu repositories (like those from many other distributions) actually forbid updating a software package except for bugfix relases ([policy](https://wiki.ubuntu.com/StableReleaseUpdates)). But we don't want that for BenchExec, users should benefit from the our latest improvements in measurement reliability, isolation, tool-info modules etc.

**Comment by MartinSpiessl** [comment] 2020-10-01 12:07
Wow, what a bummer! Now that explains a lot of the problems with outdated packages we encounter on ubuntu :expressionless: .
Do you know how that does work for browsers then? I guess they have enough (security) bugs such that an update is often necessary and they just also sneak in new features along the way:see_no_evil:.

**Comment by PhilippWendler** [comment] 2020-10-01 13:03
For a few select packages like Firefox, Thunderbird, and Chromium there are exceptions because these don't provide bugfix updates for older releases, manual backporting is too much effort in practice, and older releases rapidly become outdated because web standards evolve so fast.

Note that this is not at all particular to Ubuntu. Every non-rolling-release distro does this basically.

**Comment by PhilippWendler** [comment] 2020-10-01 13:06
More on-topic: How do we proceed with the PPA? Adding a PPA and uploading the BenchExec package was trivial (using `dput` with the `.changes` file that is produced in an intermediate step by `release.sh`, we just need to let `dpkg-buildpackage` sign it by removing `-us -uc`).

However, this then rejected:
```
Rejected:
Unable to find distroseries: unstable
Further error processing not possible because of a critical previous error.

benchexec (3.3-1) unstable; urgency=medium

  * Initial release (Closes: #nnnn)  <nnnn is the bug number of your ITP>

```
We probably just have to change that entry in our changelog, but to what value? Are you working on this because the issue is assigned to you, or should I follow up on this?

**Comment by MartinSpiessl** [comment] 2020-10-01 13:18
> Uploading the BenchExec package was trivial

Maybe for you :wink:

The plan was to leave it assigned to me until I provided everything I now, then unassign.

Please go ahead, I don't have capacity to work on this and you are the maintainer anyway, I will unassign myself.

**Comment by PhilippWendler** [comment] 2020-10-01 15:16
It's there, just needed one fix to our `debian/control` file: https://launchpad.net/~sosy-lab/+archive/ubuntu/test
Need to test it and then document it and add to `release.sh`.

**Comment by PhilippWendler** [comment] 2020-10-02 05:20
The PPA is now available.

As discussed above, I do not think it is worth the effort for adding the package to the official Ubuntu repositories, so I am closing this.

**Closed by PhilippWendler** 2020-10-02 05:20 UTC
Labels: enhancement, usability
