### ISSUE TITLE
Timestamp missing in BenchExec XML results

### ISSUE THREAD

**Issue by dbeyer** [sosy-lab/benchexec#525] opened 2019-11-23 08:52 UTC
The execution of a tool run is an event, and every event needs to come with a timestamp.
(Either start time or completion time.)

Proposal: Add appropriate tag inside the `run` tag.

BTW: The tag `date` inside `result` should be renamed to either `startdate` or `enddate`.
Furthermore, it is not a date, but a time, thus: `starttime` and `endtime`.
It is good to have this one, but strictly speaking, it can be computed (min, max)
from the above proposed tags inside each run.

**Comment by PhilippWendler** [comment] 2019-11-23 09:00
Duplicate of #221

**Closed by PhilippWendler** 2019-11-23 09:00 UTC
Labels: high priority, usability
