### ISSUE TITLE
Problem in retrieving result files in local execution of BenchExec

### ISSUE THREAD

**Issue by vmordan** [sosy-lab/benchexec#212] opened 2017-01-09 16:13 UTC
There is a problem in retrieving result files, described by `<resultfiles>*.graphml</resultfiles>` tag, from container in BenchExec (version 1.9, commit 52024e5). If we solve the following task (corresponding files are [attached](https://github.com/sosy-lab/benchexec/files/693926/task.zip)) by means of verifier cloud (benchmark.py is taken from branch 'trunk' revision 24058):

`<...>/trunk/scripts/benchmark.py --cloud --cloudUser <user>:<pass> --cloudMaster http://vcloud.sosy-lab.org/webclient -o out/ --no-compress-results --revision trunk:24058 benchmark.xml`

then witness file is added in output directory (as specified in \<resultfiles\>) as:

`out/benchmark.<...>.logfiles/cil.i.log.output/output/witness.<...>.graphml`

If we solve the same task locally by means of BenchExec 1.9 on old kernel (Ubuntu 12.04, Linux kernel 3.13, which does not support overlay filesystem):

`<...>/benchexec/bin/benchexec --no-compress-results -o out/ --container --full-access-dir / benchmark.xml`

corresponding witness file is not added in 'out' directory (but it can be found in directory `output`, which is visible and writable in the container).

If we solve the same task locally on Ubuntu 16.04, which supports overlay filesystem:

`<...>/benchexec/bin/benchexec --no-compress-results -o out/ --container benchmark.xml`

witness file is lost.

Thus, BenchExec does not retrieve result files from container during local execution. Potential reason of such behavior is parameter [`output_dir`](https://github.com/sosy-lab/benchexec/blob/52024e513568bf0e6e782a6a85f57b1a4915c81d/benchexec/containerexecutor.py#L774), which is specified in [`localexecution.py`](https://github.com/sosy-lab/benchexec/blob/52024e513568bf0e6e782a6a85f57b1a4915c81d/benchexec/localexecution.py) (function `execute`):

[`output_dir=run.result_files_folder`](https://github.com/sosy-lab/benchexec/blob/52024e513568bf0e6e782a6a85f57b1a4915c81d/benchexec/localexecution.py#L265)

During local execution this parameter was specified as:

`out/benchmark.<...>.files/cil.i`

but such output directory does not exist.

**Comment by PhilippWendler** [comment] 2017-01-09 17:55
The problem is that the specified pattern `*.graphml` does not match the created file `output/witness.<...>.graphml` according to the standard pattern matching rules. If you specify a matching pattern, the output file should be moved to `out/benchmark.<...>.files/cil.i/output/witness.<...>.graphml` (all necessary directories will be created automatically).

You could for example use `output/*.graphml` as pattern, or (if you use Python >= 3.5) also `**/*.graphml`, which recursively matches `*.graphml` in all sub-directories (not the current one).

This behavior of BenchExec comes from the Python [`glob.glob`](https://docs.python.org/3/library/glob.html#glob.glob) function, which implements the same behavior as common shells.

Does it work for you if you specify a matching pattern?

**Comment by PhilippWendler** [comment] 2017-01-09 18:10
Hm, I could special case patterns that do not contain a `/` such that they are matched against the pure file name of every result file in every directory. This is similar to what git does and would make your case work without changing the pattern.

However, this would mean we then have three different kinds of patterns instead of the current two:
- file-name patterns (do not contain `/`, matching against file name of file)
- relative-path patterns (contain a `/` not at the beginning, matching against relative path of file with respect to working directory)
- absolute-path patterns (start with `/`, matching against absolute path of file)

I am not sure whether this makes the pattern matching more useful and intuitive or too complex?

A remaining questions is whether something like `foo/` should be a file-name pattern matching directories named `foo` anywhere, or whether it should be a relative-path pattern matching a directory named `foo` in the current directory (git uses the former, but it makes the rules for explanation even more difficult).

**Comment by vmordan** [comment] 2017-01-10 13:09
Patterns `output/*.graphml` and `**/*.graphml` works both on cloud and on local launches (with Python 3.5).
Why does pattern `**.graphml` (two stars) work on cloud? What is the difference with local launch where it does not work. As I can see the pattern `**.graphml` is actively used in SVCOMP, and I supposed that it will work locally.

**Comment by vmordan** [comment] 2017-01-10 15:31
> What is the difference with local launch where it does not work.

I found out the difference -- local launch uses [BenchExec](https://github.com/sosy-lab/benchexec/blob/52024e513568bf0e6e782a6a85f57b1a4915c81d/benchexec/containerexecutor.py#L812) for that, whereas cloud uses [webclient.py](https://github.com/sosy-lab/cpachecker/blob/trunk/scripts/benchmark/webclient.py#L968).

**Comment by PhilippWendler** [comment] 2017-01-10 16:04
No, the cause for the difference is that the VerifierCloud has a completely separate implementation of the result-files matching that uses a method from the Java API and has nothing to do with BenchExec's matching. Unfortunately the Java API method for matching files has a non-standard implementation of the `**` wildcard.

This will probably change at the future such that the VerifierCloud also uses the BenchExec result-files matching.

**Comment by PhilippWendler** [comment] 2017-01-25 07:58
As the original question is answered, I am closing this issue. Please open a new issue if you have any concrete suggestions for the result-file pattern handling in BenchExec.

**Closed by PhilippWendler** 2017-01-25 07:58 UTC
Labels: question
