### ISSUE TITLE
benchexec cannot determine version of Ultimate (Automizer)

### ISSUE THREAD

**Issue by MartinSpiessl** [sosy-lab/benchexec#724] opened 2021-04-23 04:44 UTC
I currently get the following when I try to benchmark Ultimate Automizer ([the SV-COMP 2021 version](https://gitlab.com/sosy-lab/sv-comp/archives-2021/-/raw/svcomp21/2021/uautomizer.zip)):

```
/path/to/UAutomizer-linux $ benchexec @/home/user/benchexecParams ../../cpachecker/interactive/automizer.xml
2021-04-23 06:18:33,218 - WARNING - Cannot determine Ultimate version (API 2)
2021-04-23 06:18:33,585 - WARNING - Cannot determine Ultimate version (API 2)
2021-04-23 06:18:34,063 - WARNING - Cannot determine Ultimate version (API 1)
2021-04-23 06:18:34,425 - WARNING - Cannot determine Ultimate version (API 1)
Error: Cannot determine Ultimate version
$
```

I tried benchexec version 3.6 (the one that was officially used in SV-COMP), the version that ran when Ultimate Automizer zip was merged, benchexec 3.7, and the current trunk version, the problem occurs in all cases.

I tried to debug it and found out Ultimate does some call to java to determine the version, which gives me the following when I try it manually:
```
/path/to/UAutomizer-linux $ /usr/bin/java -Xss4m -jar ./plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -data @noDefault ultimatedata ./data --version
[2021-04-23 06:23:07,605 FATAL L?                        ?]: Exception during instantiation of Ultimate plugin de.uni_freiburg.informatik.ultimate.cdt.parser.CDTParser
org.eclipse.core.runtime.CoreException: Plug-in "de.uni_freiburg.informatik.ultimate.cdt.parser" was unable to instantiate class "de.uni_freiburg.informatik.ultimate.cdt.parser.CDTParser".
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:923)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginFactory.createInstance(PluginFactory.java:304)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginFactory.loadAdmissiblePlugins(PluginFactory.java:201)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginFactory.getAllAvailableToolchainPlugins(PluginFactory.java:163)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.UltimateCore.getRegisteredUltimatePlugins(UltimateCore.java:268)
        at de.uni_freiburg.informatik.ultimate.cli.options.OptionBuilder.createUltimateOptions(OptionBuilder.java:176)
        at de.uni_freiburg.informatik.ultimate.cli.options.OptionBuilder.<init>(OptionBuilder.java:77)
        at de.uni_freiburg.informatik.ultimate.cli.CommandLineParser.<init>(CommandLineParser.java:74)
        at de.uni_freiburg.informatik.ultimate.cli.CommandLineParser.createParser(CommandLineParser.java:81)
        at de.uni_freiburg.informatik.ultimate.cli.CommandLineController.init(CommandLineController.java:109)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.UltimateCore.activateController(UltimateCore.java:246)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.UltimateCore.start(UltimateCore.java:187)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/cdt/core/dom/ast/ASTVisitor
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getConstructor0(Class.java:3342)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
        ... 27 more
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.eclipse.cdt.core (90).
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:126)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
        at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:473)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 32 more
Caused by: org.osgi.framework.BundleException: Exception in org.eclipse.cdt.core.CCorePlugin.start() of bundle org.eclipse.cdt.core.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:835)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:763)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1011)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:506)
        at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
        ... 39 more
Caused by: java.lang.IllegalStateException: The instance data location has not been specified yet.
        at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:66)
        at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:136)
        at org.eclipse.core.internal.runtime.InternalPlatform.getStateLocation(InternalPlatform.java:472)
        at org.eclipse.core.runtime.Plugin.getStateLocation(Plugin.java:259)
        at org.eclipse.cdt.core.CCorePlugin.start(CCorePlugin.java:406)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:814)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:806)
        ... 46 more
This is Ultimate 0.2.0-7b2dab5
Version is 0.2.0
Maximal heap size is set to 4.2 GB
Value of java.version is 11.0.10
Value of java.specification.name is Java Platform API Specification
Value of java.specification.vendor is Oracle Corporation
Value of java.specification.version is 11
Value of java.runtime.version is 11.0.10+9-Ubuntu-0ubuntu1.20.04
Value of java.vm.name is OpenJDK 64-Bit Server VM
Value of java.vm.vendor is Ubuntu
Value of java.vm.version is 11.0.10+9-Ubuntu-0ubuntu1.20.04
An error has occurred. See the log file
/data/scratch/user/tools/UAutomizer-linux/configuration/1619151786697.log.
```

I guess the exceptions are what triggers this (otherwise the correct version output is actually there, just that the tool-info module sees the abnormal return code and decides to not even check for this, which is probably the right move). Funnily enough the exceptions don't occur on our university's computer room machines:
```
/path/to/UAutomizer-linux $ /usr/lib/jvm/java-11-openjdk-amd64/bin/java -Xss4m -jar ./plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -data @noDefault ultimatedata ./data --version
This is Ultimate 0.2.0-7b2dab5
Version is 0.2.0
Maximal heap size is set to 4,1 GB
Value of java.version is 11.0.10
Value of java.specification.name is Java Platform API Specification
Value of java.specification.vendor is Oracle Corporation
Value of java.specification.version is 11
Value of java.runtime.version is 11.0.10+9-Ubuntu-0ubuntu1.20.04
Value of java.vm.name is OpenJDK 64-Bit Server VM
Value of java.vm.vendor is Ubuntu
Value of java.vm.version is 11.0.10+9-Ubuntu-0ubuntu1.20.04
An error has occurred. See the log file
/home/user/UAutomizer-linux/configuration/1619152285975.log.
```

default for `/usr/bin/java´ is java 11 on my machine and java 8 for the computer room machines, but I tried the other java version on each machine and still the results are the same, no exceptions on the computer room machine and exceptions on my machines. All systems run ubuntu20.04. At our chair we have a machine running ubuntu 18.04, exceptions also occur there.

I thought maybe the classpath is the problem. On the computer room machines `echo $CLASSPATH` gives `.`, so I tried setting this (without luck).

I don't have any clue what could be the reason for this, maybe @Heizmann or @danieldietsch know what could be the problem here?

From the inner-most exception I would guess it has something to do with security policies/ initializing the osgi bundle, but I am no expert here:

```
Caused by: java.lang.IllegalStateException: The instance data location has not been specified yet.
        at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:66)
        at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:136)
        at org.eclipse.core.internal.runtime.InternalPlatform.getStateLocation(InternalPlatform.java:472)
        at org.eclipse.core.runtime.Plugin.getStateLocation(Plugin.java:259)
        at org.eclipse.cdt.core.CCorePlugin.start(CCorePlugin.java:406)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:814)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:806)
```

Maybe I also did make a stupid mistake, I am open for suggestions what else to try.

**Comment by PhilippWendler** [comment] 2021-04-23 06:39
Actually, the first question to answer would be: Does this problem also occur if you start Ultimate manually, either for verification or for retrieving the version number? If yes, it seems unlikely to be related to BenchExec.

**Comment by danieldietsch** [comment] 2021-04-23 07:16
So, one strange thing is the call at the beginning:
``/usr/bin/java -Xss4m -jar ./plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -data @noDefault ultimatedata ./data --version``

It should actually be ``-ultimatedata``.

If this does not help: Can you add the log file ``/home/user/UAutomizer-linux/configuration/1619152285975.log`` ? 

Some other hints:
* Since 0.2.0, Ultimate requires Java 11, so no need to test with Java 8.  
* In some cases it can happen that the Ultimate data directory becomes corrupt. It helps to delete this directory (which is usually specified with ``-ultimatedata``). It can also help to delete everything under ``configuration`` except ``config.ini`` and ``org.eclipse.update``.

**Comment by danieldietsch** [comment] 2021-05-03 07:21
@MartinSpiessl did you make it work?

**Comment by MartinSpiessl** [comment] 2021-05-03 07:54
Partially, I still have my writeup on disk and planned to post when I got time to continue

> If this does not help: Can you add the log file /home/user/UAutomizer-linux/configuration/1619152285975.log ?
Sure, here it is:
[1619152285975.log](https://github.com/sosy-lab/benchexec/files/6366456/1619152285975.log)
Seems like the errors are also there, but not written to stdout.


> Since 0.2.0, Ultimate requires Java 11, so no need to test with Java 8.

Understood, so this is not the problem. Java 11 is default on most machines here anyway.


> It should actually be -ultimatedata.

Oh, there I must have made some error during copy&paste. This explains a lot. With the `-ultimatedata` no errors occur anymore, but benchexec still can't determine the version. I hacked benchexec to show me the error output from Ultimate, here it is:
```
!SESSION 2021-04-23 17:50:09.793 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_282
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en

!ENTRY org.eclipse.osgi 4 0 2021-04-23 17:50:09.990
!MESSAGE Error reading configuration: /data/scratch/user/tools/UAutomizer-linux/configuration/org.eclipse.osgi/.manager/.fileTableLock (Operation not supported)
!STACK 0
java.io.FileNotFoundException: /data/scratch/user/tools/UAutomizer-linux/configuration/org.eclipse.osgi/.manager/.fileTableLock (Operation not supported)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at org.eclipse.osgi.internal.location.Locker_JavaNio.lock(Locker_JavaNio.java:40)
        at org.eclipse.osgi.storagemanager.StorageManager.lock(StorageManager.java:403)
        at org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:716)
        at org.eclipse.osgi.storage.Storage.getChildStorageManager(Storage.java:2262)
        at org.eclipse.osgi.storage.Storage.getInfoInputStream(Storage.java:2279)
        at org.eclipse.osgi.storage.Storage.<init>(Storage.java:252)
        at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:180)
        at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:113)
        at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:53)
        at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:46)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:315)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

This could have to do with the directory layout on our machines. Afaik benchexec does some containerization when it executes the tool for determining the version. I still have to try whether this works on my machine locally (not on that machine from which we usually start benchmarks where there might be a strange interaction between the overlayfs and nfs or something), that is what I was initially still waiting for before posting this. I might get around to this soon, or maybe @PhilippWendler already has an idea what this might be caused by.

The file `/data/scratch/user/tools/UAutomizer-linux/configuration/org.eclipse.osgi/.manager/.fileTableLoc` seems to be there on my disk. After deleting it however the error message does **not** change. 

I now tried to mark the dir with this file as full-access-dir (via benchexec's command line options), now that warning is gone but ultimate seems to struggle to find some dependencies:

```
Value of java.vm.vendor is Ubuntu
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                  -> Bundle-SymbolicName: de.uni_freiburg.informatik.ultimate.plugins.generator.rcfgbuilder; bundle-version="0.2.0"; singleton:="true"
    -> Bundle-SymbolicName: de.uni_freiburg.informatik.ultimate.plugins.generator.buchiautomizer; bundle-version="0.2.0"; singleton:="true"
org.osgi.framework.BundleException: Could not resolve module: de.uni_freiburg.informatik.ultimate.chcprinter [16]
         Unresolved requirement: Require-Bundle: de.uni_freiburg.informatik.ultimate.lib.modelcheckerutils
    -> Bundle-SymbolicName: de.uni_freiburg.informatik.ultimate.lib.automata; bundle-version="0.2.0"
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
  Unresolved requirement: Require-Bundle: de.uni_freiburg.informatik.ultimate.lib.icfgtransformer
  Unresolved requirement: Require-Bundle: de.uni_freiburg.informatik.ultimate.plugins.generator.rcfgbuilder
[...]
```

I think I know now what is going on. If I configure `--full-access-dir /data/scratch/user/tools/UAutomizer-linux` then the problem is gone and I can execute Ultimate :tada:.

I recall we discussed that `REQUIRED_PATH` from the tool info modules is error-prone since some tools had problems in SV-COMP 2021 preruns because of files that were not transferred to the cloud system. The SV-COMP organizer as a result probably set `--full-access-dir <tooldir>` for all tools proactively. So maybe there is something missing in Ultimate's `REQUIRED_PATH` and that didn't show up in SV-COMP because of that? Or something very similar.

Anyway my problem is solved for now, but I will leave this issue open as there might still be something that needs fixing (don't have time now to debug further, I might come back in 1-2 weeks and revisit this unless it is already solved).

**Comment by danieldietsch** [comment] 2021-05-03 08:16
Yes, Ultimate needs write permissions to its ``configuration`` and ``data`` directory. Is there any way to specify that in the tool-info module?
And you should not need to hack benchexec to get the full output, the option ``<option name="--full-output"/>`` should do that.

**Comment by PhilippWendler** [comment] 2021-05-03 10:27
General note: Remember that there is a [utility](https://github.com/sosy-lab/benchexec/blob/master/doc/tool-integration.md#testing-the-tool-integration) for testing tool integrations and related problems. Cases like this can be investigated faster with it than attempting a full `benchexec` run each time.

> I hacked benchexec to show me the error output from Ultimate, here it is:

Just using `--debug` should have been enough, it seems, there are respective logging statements in the code. (For `test_tool_info`, this was previously not available, but now it is there as well.)

> Afaik benchexec does some containerization when it executes the tool for determining the version.

Yes, and for debugging one can easily disable it with `--no-container` do determine whether the problem is related to containerization or not.

> there might be a strange interaction between the overlayfs and nfs or something

Yes, given the `Operation not supported` error message, this is likely to be the case. This is actually even already listed in our [container troubleshooting docs](https://github.com/sosy-lab/benchexec/blob/master/doc/container.md#problems-when-accessing-files-in-container-process-dies-operation-not-supported-no-such-device-or-address).

> I now tried to mark the dir with this file as full-access-dir

Note that in general I would recommend as a first step to try `--read-only-dir` to not give overly broad permissions unless necessary.

When experiencing problems where one suspects that it might be related to the underlying file system, the quickest way to test is to do `--read-only-dir /mountpoint` or even `--read-only-dir /`. Then one can narrow it down further if necessary (but often this is already sufficient depending on where write permissions are needed).

> I recall we discussed that `REQUIRED_PATH` from the tool info modules is error-prone since some tools had problems in SV-COMP 2021 preruns because of files that were not transferred to the cloud system.

Yes, but this is completely unrelated to the current issue.

> The SV-COMP organizer as a result probably set `--full-access-dir <tooldir>` for all tools proactively.

No, `--full-access-dir` is not used in SV-COMP. That would decrease reproducibility and is undesired.

> Yes, Ultimate needs write permissions to its `configuration` and `data` directory.

Note that independently of the current issue, I find tools more user friendly if the never write to their installation directories. Doing so causes trouble for example when several users want to share an installation of a tool or one wants to put it into `/opt` or similar directories.

It would also be nice if Ultimate would not attempt to write anything when just its version is retrieved. Users certainly do not expect tools to modify files on their disk as part of this.

> Is there any way to specify that in the tool-info module?

No, we don't want to be able to let the tool-info module request write permission behind the back of the user. If the user wants to give write permission to a tool and accept the risks related to that, they need to request this explicitly. (In most cases, it is not necessary because overlayfs takes care of this transparently and safely.)

> I will leave this issue open as there might still be something that needs fixing

Maybe the tool-info module of Ultimate could be improved such that it provides a more useful error message (indicating for example a missing write permission)? For example, I would suggest for Ultimate to provide a proper user-targeted error message instead of a stack trace for developers, and then the tool-info module could forward that message? But I leave it to @danieldietsch to decide whether this is possible and planned. Otherwise we will close this this issue.

**Comment by danieldietsch** [comment] 2021-05-03 11:32
> Note that independently of the current issue, I find tools more user friendly if the never write to their installation directories.

Me too, but it is difficult to achieve for us due to our base platform (RCP) and has very low priority. 

> Maybe the tool-info module of Ultimate could be improved such that it provides a more useful error message (indicating for example a missing write permission)?

Yes, but our tool-info module is already one of the most complex ones. Before I add a custom error message for this behavior, I try and find out if we can avoid writing altogether. 

Nevertheless, I would like to know why this issue did not occur during SV-COMP 2021, i.e., what was the difference then?

**Comment by PhilippWendler** [comment] 2021-05-03 11:47
> Nevertheless, I would like to know why this issue did not occur during SV-COMP 2021, i.e., what was the difference then?

There was no NFS for the tool directory.

**Closed** 2021-05-07 06:17 UTC
Labels: tool support
